# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: Build-$(Build.BuildId)

trigger: none
pr: [dev]

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: TerraformInstaller@0
  displayName: 'Install Terraform version $(TF-Version)'
  inputs:
    terraformVersion: '$(TF-Version)'
- script: terraform init -get=true -upgrade=true -backend-config='storage_account_name=$(sa-name)' -backend-config='container_name=$(blob-name)' -backend-config='access_key=$(sa-key)' -backend-config='key=$(key)'
  workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'Terraform Init'
- script: terraform workspace select '$(Dev-WS)' || terraform workspace new '$(Dev-WS)'
  workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'Switch to Environment $(Dev-WS)'
- script: 'terraform validate -var="subscription_id=$(subscription-id)" -var="client_id=$(client-id)" -var="client_secret=$(client-secret)" -var="tenant_id=$(tenant-id)" -var="repo_name=$(repo_name)" -var="repo_username=$(repo_username)" -var="repo_password=$(repo_password)"'
  workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'Validate Terraform Code'
- script: 'terraform plan -lock=true -var="subscription_id=$(subscription-id)" -var="client_id=$(client-id)" -var="client_secret=$(client-secret)" -var="tenant_id=$(tenant-id)" -var="repo_name=$(repo_name)" -var="repo_username=$(repo_username)" -var="repo_password=$(repo_password)"'
  workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'Terraform Dry Run (Plan)'