# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(Date:yyyyMMdd)$(Rev:.r)
pr: none

variables:
- name: TF_WORKSPACE
  value: default

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'azure.tfvars'
- task: TerraformInstaller@0
  inputs:
    terraformVersion: '0.12.3'
- task: CmdLine@2
  displayName: Initialize Terraform
  inputs:
    script: 'terraform init -get=true -upgrade=true -backend-config=$(Agent.TempDirectory)\azure.tfvars'
    workingDirectory: '$(Build.SourcesDirectory)'
- task: CmdLine@2
  displayName: Validate Terraform Code
  inputs:
    script: 'terraform validate'
    workingDirectory: '$(Build.SourcesDirectory)'
- task: CmdLine@2
  displayName: Test Terraform Code (Plan)
  inputs:
    script: 'terraform plan -var-file=$(Agent.TempDirectory)\azure.tfvars'
    workingDirectory: '$(Build.SourcesDirectory)'