# Terraform CI Pipeline

name: $(Date:yyyyMMdd)$(Rev:.r)-$(Build.BuildId)

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - azure-pipelines.yml

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureKeyVault@1
  displayName: 'Download Key Vault Secrets'
  inputs:
    azureSubscription: 'Azure MSDN'
    KeyVaultName: 'DevOps-Terraform-KV'
- task: TerraformInstaller@0
  displayName: 'Install Terraform version $(TF-Version)'
  inputs:
    terraformVersion: '$(TF-Version)'
- template: templates/terraform.yml
  parameters:
    sa-name: '$(sa-name)'
    blob-name: '$(blob-name)'
    sa-key: '$(sa-key)'
    state-key: '$(key)'
    workspace: '$(TF-Workspace)'
    subscription--id: '$(subscription-id)'
    client-id: '$(client-id)'
    client-secret: '$(client-secret)'
    tenant-id: '$(tenant-id)'
