# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

variables:
- group: terraform-azure-backend
- group: terraform-azure-creds

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: '0.12.3'
- task: TerraformInit@0
  inputs:
    command: 'init'
    commandOptions: '-get=true -upgrade=true'
    backendType: 'azurerm'
    backendServiceArm: 'Azure Dev Account'
    backendAzureRmResourceGroupName: '$(RESOURCE_GROUP)'
    backendAzureRmStorageAccountName: '$(STORAGE_ACCOUNT)'
    backendAzureRmContainerName: '$(BLOB)'
    backendAzureRmKey: 'terraform-ci-cd-demo.tfstate'
- task: TerraformValidate@0
  inputs:
    command: 'validate'