# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(Date:yyyyMMdd)$(Rev:.r)
pr: none

variables:
  TF_WORKSPACE: default
- group: terraform-azure-backend
- group: terraform-azure-creds

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: '0.12.3'
- task: TerraformCLI@0
  displayName: Initialize Terraform
  inputs:
    command: 'init'
    commandOptions: '-get=true -upgrade=true'
    backendType: 'azurerm'
    backendServiceArm: 'Azure Dev Account'
    backendAzureRmResourceGroupName: '$(RESOURCE_GROUP)'
    backendAzureRmStorageAccountName: '$(STORAGE_ACCOUNT)'
    backendAzureRmContainerName: '$(BLOB)'
    backendAzureRmKey: 'terraform-ci-cd-demo.tfstate'
- task: TerraformCLI@0
  displayName: Validate Terraform Code
  inputs:
    command: 'validate'
- task: TerraformCLI@0
  displayName: Terraform Unit Testing (Plan)
  inputs:
    command: 'plan'
    commandOptions: '-out=$(TF_WORKSPACE)-$(Build.BuildId).plan'
    environmentServiceName: 'Azure Dev Account'