# Terraform CI Pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(Date:yyyyMMdd)$(Rev:.r)
trigger: [master]
pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DownloadSecureFile@1
  displayName: Download Azure Backend Connection Details
  inputs:
    secureFile: 'backend.tfvars'
- task: TerraformInstaller@0
  displayName: 'Install Terraform version $(TF-Version)'
  inputs:
    terraformVersion: '$(TF-Version)'
- script: terraform init -get=true -upgrade=true -backend-config=$(Agent.TempDirectory)/backend.tfvars
  workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'Terraform Init'
- script: terraform workspace select dev || terraform workspace new dev
  workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'Terraform workspace'