# Terraform CI Pipeline

name: Build-$(Build.BuildId)

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - azure-pipelines.yml
pr: none

jobs:
- job: dev
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: TerraformInstaller@0
    displayName: 'Install Terraform version $(TF-Version)'
    inputs:
      terraformVersion: '$(TF-Version)'
  - template: templates/terraform.yml
    parameters:
      saName: '$(sa-name)'
      blobName: '$(blob-name)'
      saKey: '$(sa-key)'
      stateKey: '$(key)'
      workspace: '$(Dev-WS)'
      subscriptionId: '$(subscription-id)'
      clientId: '$(client-id)'
      clientSecret: '$(client-secret)'
      tenantId: '$(tenant-id)'
- job: test
  dependsOn: 'dev'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: TerraformInstaller@0
    displayName: 'Install Terraform version $(TF-Version)'
    inputs:
      terraformVersion: '$(TF-Version)'
  - template: templates/terraform.yml
    parameters:
      saName: '$(sa-name)'
      blobName: '$(blob-name)'
      saKey: '$(sa-key)'
      stateKey: '$(key)'
      workspace: '$(Test-WS)'
      subscriptionId: '$(subscription-id)'
      clientId: '$(client-id)'
      clientSecret: '$(client-secret)'
      tenantId: '$(tenant-id)'
- job: stage
  dependsOn: ['dev', 'test']
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: TerraformInstaller@0
    displayName: 'Install Terraform version $(TF-Version)'
    inputs:
      terraformVersion: '$(TF-Version)'
  - template: templates/terraform.yml
    parameters:
      saName: '$(sa-name)'
      blobName: '$(blob-name)'
      saKey: '$(sa-key)'
      stateKey: '$(key)'
      workspace: '$(Stage-WS)'
      subscriptionId: '$(subscription-id)'
      clientId: '$(client-id)'
      clientSecret: '$(client-secret)'
      tenantId: '$(tenant-id)'
- job: prod
  dependsOn: ['dev', 'test', 'stage']
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: TerraformInstaller@0
    displayName: 'Install Terraform version $(TF-Version)'
    inputs:
      terraformVersion: '$(TF-Version)'
  - template: templates/terraform.yml
    parameters:
      saName: '$(sa-name)'
      blobName: '$(blob-name)'
      saKey: '$(sa-key)'
      stateKey: '$(key)'
      workspace: '$(Production-WS)'
      subscriptionId: '$(subscription-id)'
      clientId: '$(client-id)'
      clientSecret: '$(client-secret)'
      tenantId: '$(tenant-id)'