# Terraform CI Pipeline

name: $(Date:yyyyMMdd)$(Rev:.r)-$(Build.BuildId)

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - azure-pipelines.yml
pr: none

jobs:
- job: dev
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: AzureKeyVault@1
    displayName: 'Download Key Vault Secrets'
    inputs:
      azureSubscription: 'Azure MSDN'
      KeyVaultName: 'DevOps-Terraform-KV'
  - task: TerraformInstaller@0
    displayName: 'Install Terraform version $(TF-Version)'
    inputs:
      terraformVersion: '$(TF-Version)'
  - template: templates/terraform.yml
    parameters:
      saName: '$(sa-name)'
      blobName: '$(blob-name)'
      saKey: '$(sa-key)'
      stateKey: '$(key)'
      workspace: 'dev'
      subscriptionId: '$(subscription-id)'
      clientId: '$(client-id)'
      clientSecret: '$(client-secret)'
      tenantId: '$(tenant-id)'
- job: test
  dependsOn: 'dev'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: AzureKeyVault@1
    displayName: 'Download Key Vault Secrets'
    inputs:
      azureSubscription: 'Azure MSDN'
      KeyVaultName: 'DevOps-Terraform-KV'
  - task: TerraformInstaller@0
    displayName: 'Install Terraform version $(TF-Version)'
    inputs:
      terraformVersion: '$(TF-Version)'
  - template: templates/terraform.yml
    parameters:
      saName: '$(sa-name)'
      blobName: '$(blob-name)'
      saKey: '$(sa-key)'
      stateKey: '$(key)'
      workspace: 'test'
      subscriptionId: '$(subscription-id)'
      clientId: '$(client-id)'
      clientSecret: '$(client-secret)'
      tenantId: '$(tenant-id)'
- job: stage
  dependsOn: ['dev', 'test']
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: AzureKeyVault@1
    displayName: 'Download Key Vault Secrets'
    inputs:
      azureSubscription: 'Azure MSDN'
      KeyVaultName: 'DevOps-Terraform-KV'
  - task: TerraformInstaller@0
    displayName: 'Install Terraform version $(TF-Version)'
    inputs:
      terraformVersion: '$(TF-Version)'
  - template: templates/terraform.yml
    parameters:
      saName: '$(sa-name)'
      blobName: '$(blob-name)'
      saKey: '$(sa-key)'
      stateKey: '$(key)'
      workspace: 'stg'
      subscriptionId: '$(subscription-id)'
      clientId: '$(client-id)'
      clientSecret: '$(client-secret)'
      tenantId: '$(tenant-id)'
- job: prod
  dependsOn: ['dev', 'test', 'stage']
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: AzureKeyVault@1
    displayName: 'Download Key Vault Secrets'
    inputs:
      azureSubscription: 'Azure MSDN'
      KeyVaultName: 'DevOps-Terraform-KV'
  - task: TerraformInstaller@0
    displayName: 'Install Terraform version $(TF-Version)'
    inputs:
      terraformVersion: '$(TF-Version)'
  - template: templates/terraform.yml
    parameters:
      saName: '$(sa-name)'
      blobName: '$(blob-name)'
      saKey: '$(sa-key)'
      stateKey: '$(key)'
      workspace: 'prod'
      subscriptionId: '$(subscription-id)'
      clientId: '$(client-id)'
      clientSecret: '$(client-secret)'
      tenantId: '$(tenant-id)'