# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
- group: terraform-azure-backend

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: '0.12.3'
- task: TerraformCLI@0
  inputs:
    command: 'init -backend-config="storage_account_name=$(STORAGE_ACCOUNT)" \
    -backend-config="container_name=$(BLOB)" \
    -backend-config="access_key=$(ACCESS_KEY)" \
    -backend-config="key=terraform-ci-cd-demo.tfstate" \
    -get=true \
    -upgrade=true'